version: "3"
   
services:
  redis:
    image: "redis:alpine"
  jerry:
    build: .
    command: python3 backend/manage.py runserver 0.0.0.0:9000
    volumes:
      - ./:/code
    ports:
      - "9000:9000"
    depends_on:
      - redis